import { useEffect, useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import Navbar from "./ui/Navbar";
import "../css/quiz.css";

type Skill = {
    skill_id: number;
    skill_name: string;
    category: string;
};

type QuizQuestion = {
    question_id: number;
    question_text: string;
    option_a: string;
    option_b: string;
    option_c: string;
    option_d: string;
    difficulty: "Beginner" | "Intermediate" | "Advanced";
};

type QuizResult = {
    score: number;
    total_questions: number;
    percentage: number;
    level: "Beginner" | "Developing" | "Proficient";
    recommendation: string;
};

function Quiz() {

    const navigate = useNavigate();

    const [skills, setSkills] = useState<Skill[]>([]);
    const [selectedSkill, setSelectedSkill] = useState<number | null>(null);

    const [questions, setQuestions] = useState<QuizQuestion[]>([]);
    const [currentQuestion, setCurrentQuestion] = useState(0);

    const [answers, setAnswers] = useState<Record<number, string>>({});

    // Stores the unique quiz generated by the backend.
    const [quizId, setQuizId] = useState<string | null>(null);

    const [loading, setLoading] = useState(false);
    const [loadingSkills, setLoadingSkills] = useState(true);

    const [quizStarted, setQuizStarted] = useState(false);
    const [result, setResult] = useState<QuizResult | null>(null);

    const token = localStorage.getItem("token");

    const headers = {
        Authorization: `Bearer ${token}`
    };


    // Load user's selected skills
    useEffect(() => {

        const loadSkills = async () => {

            try {

                const response = await axios.get(
                    "/api/skills/user",
                    { headers }
                );

                const userSkills: Skill[] = response.data;

                /*
                 * AI generates quiz questions dynamically.
                 *
                 * Therefore, we no longer need to check
                 * whether questions already exist in the
                 * database for each skill.
                 */
                setSkills(userSkills);

            } catch (error) {

                console.error(
                    "LOAD QUIZ SKILLS ERROR:",
                    error
                );

            } finally {

                setLoadingSkills(false);

            }
        };

        loadSkills();

    }, []);


    // Start AI-generated quiz for selected skill
    const startQuiz = async () => {

        if (!selectedSkill) {
            alert("Please select a skill first.");
            return;
        }

        try {

            setLoading(true);

            /*
             * Ask the backend to generate a new quiz
             * using Gemini 3.6 Flash.
             */
            const response = await axios.get(
                `/api/quiz/generate/${selectedSkill}`,
                { headers }
            );

            if (
                !response.data ||
                !response.data.questions ||
                response.data.questions.length === 0
            ) {
                alert("Unable to generate a quiz for this skill.");
                return;
            }

            /*
             * Store the unique quiz ID.
             *
             * This ID is required when submitting
             * the answers.
             */
            setQuizId(response.data.quiz_id);

            setQuestions(response.data.questions);
            setCurrentQuestion(0);
            setAnswers({});
            setResult(null);
            setQuizStarted(true);

        } catch (error) {

            console.error(
                "GENERATE AI QUIZ ERROR:",
                error
            );

            alert(
                "Unable to generate the quiz right now. Please try again."
            );

        } finally {

            setLoading(false);

        }
    };


    // Select an answer
    const selectAnswer = (option: string) => {

        const question = questions[currentQuestion];

        setAnswers(prev => ({
            ...prev,
            [question.question_id]: option
        }));

    };


    // Go to next question
    const handleNext = () => {

        if (currentQuestion < questions.length - 1) {

            setCurrentQuestion(prev => prev + 1);

        }

    };


    // Go to previous question
    const handlePrevious = () => {

        if (currentQuestion > 0) {

            setCurrentQuestion(prev => prev - 1);

        }

    };


    // Submit quiz
    const submitQuiz = async () => {

        if (Object.keys(answers).length !== questions.length) {

            alert(
                "Please answer all questions before submitting."
            );

            return;
        }

        if (!quizId) {

            alert(
                "Quiz session not found. Please start the quiz again."
            );

            return;
        }

        try {

            setLoading(true);

            /*
             * Convert the selected answers into the
             * format expected by the backend.
             */
            const formattedAnswers = questions.map(question => ({
                question_id: question.question_id,
                selected_option: answers[question.question_id]
            }));

            /*
             * Submit both:
             *
             * 1. quiz_id
             * 2. answers
             *
             * The backend uses quiz_id to retrieve the
             * correct answers stored on the server.
             */
            const response = await axios.post(
                "/api/quiz/submit",
                {
                    quiz_id: quizId,
                    answers: formattedAnswers
                },
                {
                    headers
                }
            );

            setResult(response.data);

            setQuizStarted(false);

            /*
             * The quiz is deleted by the backend after
             * successful submission, so clear the local ID.
             */
            setQuizId(null);

        } catch (error) {

            console.error(
                "SUBMIT QUIZ ERROR:",
                error
            );

            alert(
                "Failed to submit quiz. Please try again."
            );

        } finally {

            setLoading(false);

        }
    };


    // Restart quiz
    const retakeQuiz = () => {

        setQuestions([]);
        setAnswers({});
        setCurrentQuestion(0);
        setQuizId(null);
        setResult(null);
        setQuizStarted(false);

    };


    // Loading skills
    if (loadingSkills) {

        return (
            <div className="dashboard-layout">

                <Navbar />

                <main className="dashboard-content">

                    <div className="quiz-loading">
                        Loading your skills...
                    </div>

                </main>

            </div>
        );

    }


    // Quiz result



    // Skill selection screen
    if (!quizStarted) {

        return (

            <div className="dashboard-layout">

                <Navbar />

                <main className="dashboard-content">

                    <div className="quiz-header">

                        <div>

                            <p className="dashboard-label">
                                PERSONALIZED SKILL QUIZ
                            </p>

                            <h1>
                                Test Your Knowledge
                            </h1>

                            <p>
                                Select a skill and take a short
                                AI-generated quiz to check your
                                current knowledge level.
                            </p>

                        </div>

                    </div>


                    {skills.length === 0 ? (

                        <section className="quiz-empty-card">

                            <h2>
                                No Selected Skills
                            </h2>

                            <p>
                                Select some skills first before
                                taking a quiz.
                            </p>

                            <button
                                onClick={() =>
                                    navigate("/skills-setup")
                                }
                            >
                                Select Skills →
                            </button>

                        </section>

                    ) : (

                        <section className="quiz-selection-card">

                            <h2>
                                Choose a Skill
                            </h2>

                            <p>
                                Choose one of your selected skills
                                to generate your personalized AI quiz.
                            </p>


                            <div className="quiz-skill-list">

                                {skills.map(skill => (

                                    <button
                                        key={skill.skill_id}
                                        className={
                                            selectedSkill === skill.skill_id
                                                ? "quiz-skill selected"
                                                : "quiz-skill"
                                        }
                                        onClick={() =>
                                            setSelectedSkill(
                                                skill.skill_id
                                            )
                                        }
                                    >

                                        <div>

                                            <strong>
                                                {skill.skill_name}
                                            </strong>

                                            <span>
                                                {skill.category}
                                            </span>

                                        </div>

                                    </button>

                                ))}

                            </div>


                            <button
                                className="quiz-start-button"
                                onClick={startQuiz}
                                disabled={
                                    !selectedSkill || loading
                                }
                            >
                                {loading
                                    ? "Generating Quiz..."
                                    : "Start Quiz →"}
                            </button>

                        </section>

                    )}
                    {result && (
                        <div className="quiz-result-overlay">

                            <section className="quiz-result-popup">

                                <button
                                    className="quiz-result-close"
                                    onClick={() => setResult(null)}
                                    aria-label="Close result"
                                >
                                    ×
                                </button>

                                <p className="dashboard-label">
                                    QUIZ RESULT
                                </p>

                                <h1>
                                    {result.percentage}%
                                </h1>

                                <h2>
                                    {result.level}
                                </h2>

                                <p className="quiz-score">
                                    You scored {result.score} out of{" "}
                                    {result.total_questions}
                                </p>

                                <div className="quiz-recommendation">

                                    <h3>
                                        Recommendation
                                    </h3>

                                    <p>
                                        {result.recommendation}
                                    </p>

                                </div>

                                <div className="quiz-result-actions">

                                    <button
                                        className="quiz-primary-button"
                                        onClick={retakeQuiz}
                                    >
                                        Retake Quiz
                                    </button>

                                    <button
                                        className="quiz-secondary-button"
                                        onClick={() =>
                                            navigate("/progress")
                                        }
                                    >
                                        View Progress
                                    </button>

                                </div>

                            </section>

                        </div>
                    )}
                </main>

            </div>

        );

    }


    // Current question
    const question = questions[currentQuestion];

    const selectedAnswer =
        answers[question.question_id];


    return (

        <div className="dashboard-layout">

            <Navbar />

            <main className="dashboard-content">

                <section className="quiz-question-card">

                    <div className="quiz-question-header">

                        <div>

                            <p className="dashboard-label">
                                PERSONALIZED SKILL QUIZ
                            </p>

                            <h1>
                                Question {currentQuestion + 1} of{" "}
                                {questions.length}
                            </h1>

                        </div>

                        <span className="quiz-progress-text">
                            {Math.round(
                                ((currentQuestion + 1) /
                                    questions.length) *
                                100
                            )}%
                        </span>

                    </div>


                    <div className="quiz-question-progress">

                        <div
                            style={{
                                width: `${((currentQuestion + 1) /
                                    questions.length) *
                                    100
                                    }%`
                            }}
                        />

                    </div>


                    <div className="quiz-question-content">

                        <h2>
                            {question.question_text}
                        </h2>


                        <div className="quiz-options">

                            {[
                                ["A", question.option_a],
                                ["B", question.option_b],
                                ["C", question.option_c],
                                ["D", question.option_d]
                            ].map(([letter, text]) => (

                                <button
                                    key={letter}
                                    className={
                                        selectedAnswer === letter
                                            ? "quiz-option selected"
                                            : "quiz-option"
                                    }
                                    onClick={() =>
                                        selectAnswer(letter)
                                    }
                                >

                                    <span className="quiz-option-letter">
                                        {letter}
                                    </span>

                                    <span>
                                        {text}
                                    </span>

                                </button>

                            ))}

                        </div>

                    </div>


                    <div className="quiz-navigation">

                        <button
                            className="quiz-secondary-button"
                            onClick={handlePrevious}
                            disabled={currentQuestion === 0}
                        >
                            ← Previous
                        </button>


                        {currentQuestion === questions.length - 1 ? (

                            <button
                                className="quiz-primary-button"
                                onClick={submitQuiz}
                                disabled={loading}
                            >
                                {loading
                                    ? "Submitting..."
                                    : "Submit Quiz"}
                            </button>

                        ) : (

                            <button
                                className="quiz-primary-button"
                                onClick={handleNext}
                            >
                                Next →
                            </button>

                        )}

                    </div>

                </section>

            </main>

        </div>

    );
}

export default Quiz;